### ISSUE TITLE
[BZM] Zelda Minish Cap - Can't get out of sleep mode.

### ISSUE THREAD

**Issue by Arignir** [hades-emu/Hades#13]
If you go to the menu, press "SLEEP" then "YES", it enables the sleep mode. 

There's a similar features in many other games (Metroid Fusion is the one that immediately comes to mind) but it doesn't seem like we get out of this one correctly. 

Game Name: `The Legend of Zelda - The Minish Cap`
Game Code: `BZM`

**Comment by Atem2069** [comment]
if you still have this issue, sleep/STOP mode seems to exit if just the condition in KEYCNT is met (i.e. it doesn't have to actually trigger an IRQ, and KEYCNT.14 doesn't affect whether STOP mode exits or not).

**Comment by Arignir** [comment]
Fixed with https://github.com/hades-emu/Hades/pull/74
