### ISSUE TITLE
[A2Y] Top Gun - Combat Zones (USA) - Stuck on main menu

### ISSUE THREAD

**Issue by benderscruffy** [hades-emu/Hades#29]
stuck on the menu screen

**Comment by Arignir** [comment]
Hello,

I could confirm the issue, there's no way to get past the menu screen.

![image](https://user-images.githubusercontent.com/4798413/210356755-4b7ff354-14e9-4657-a7d0-ec52b95e8ac1.png)

I'll look into it!

Game Name: `Top Gun - Combat Zones`
Game Code: `A2Y`

Thank you for your support and for taking the time to check on my project ~

**Comment by Arignir** [comment]
The game includes anti-piracy measures that would incorrectly detect its backup storage as Flash64.  In practice, the game has no backup storage.
