### ISSUE TITLE
[DEMO] video_capture.gba does not display properly

### ISSUE THREAD

**Issue by benderscruffy** [hades-emu/Hades#30]
[video_capture.zip](https://github.com/Arignir/Hades/files/10323078/video_capture.zip)

**Comment by Arignir** [comment]
Hello,

I can confirm the issue. Here's the current output in the most recent version of Hades:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/4798413/210470795-069aca76-69cc-4efa-a27a-48de371b9ddb.png">

And here's the output in NanoBoyAdvance:

<img width="470" alt="image" src="https://user-images.githubusercontent.com/4798413/210470841-118b4b44-d105-46dd-8c07-056b8c995c66.png">

I'll look into it!

Thank you for your support and for taking the time to check on my project ~

**Comment by Arignir** [comment]
References:

- https://github.com/mgba-emu/mgba/issues/2017
- https://github.com/skylersaleh/SkyEmu/issues/104
