### ISSUE TITLE
[AKT] Hello Kitty Collection - Miracle Fashion Maker | Black screen on boot

### ISSUE THREAD

**Issue by benderscruffy** [hades-emu/Hades#31]
nothing but a black screen

**Comment by Arignir** [comment]
Hello,

I knew about that one. It's famous for being hard to emulate :D 

I'll try my best to fix it!

Game Name: `Hello Kitty Collection - Miracle Fashion Maker`
Game Code: `AKT`

Thank you for your support and for taking the time to check on my project ~

**Comment by Arignir** [comment]
Finally fixed after a lot of improvements regarding DMA's open bus behavior.

@endrift's blog post "[The Infinite Loop That Wasn't: A Holy Grail Bug Story](https://mgba.io/2020/01/25/infinite-loop-holy-grail/)" explains how and why this bug happens.
