### ISSUE TITLE
[AYC] Phantasy Star Collection - All texts are rendered twice

### ISSUE THREAD

**Issue by benderscruffy** [hades-emu/Hades#37]
![2023-01-02_12h20m51s](https://user-images.githubusercontent.com/2696404/210195149-5a91d071-7e5c-48f3-8b3a-a13ee6b1bc0c.png)

**Comment by Arignir** [comment]
Hello,

I could confirm the issue, I'll look into it! The whole game is also slightly flickering, which is a bit annoying.

Game Name: `Phantasy Star Collection`
Game Code: `AYC`

Thank you for your support and for taking the time to check on my project ~

**Comment by Arignir** [comment]
Fixed when improving the current implementation of DMA open bus. I've opened [a new issue](https://github.com/hades-emu/Hades/issues/81) for the slight flickering.
